# -*- coding: utf-8 -*-
"""PSO Problem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIstvHHPBB4i0if1ipPii_aQIdRk0tbH
"""

import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

np.random.seed(42)
X = np.random.rand(100, 5)
y = np.random.randint(0, 2, 100)

num_particles = 6
num_features = 5
max_iter = 10

w = 0.7
c1 = 2
c2 = 2

def evaluate(mask):
    """Return accuracy of Decision Tree using selected features."""


    if np.sum(mask) == 0:
        return 0

    selected = X[:, mask == 1]

    X_train, X_test, y_train, y_test = train_test_split(
        selected, y, test_size=0.3, random_state=42
    )

    clf = DecisionTreeClassifier()
    clf.fit(X_train, y_train)
    pred = clf.predict(X_test)

    return accuracy_score(y_test, pred)

particles = np.random.randint(0, 2, (num_particles, num_features))
velocities = np.random.uniform(-1, 1, (num_particles, num_features))

personal_best = particles.copy()
personal_best_scores = np.array([evaluate(p) for p in particles])


best_idx = np.argmax(personal_best_scores)
global_best = personal_best[best_idx].copy()
global_best_score = personal_best_scores[best_idx]

print("Initial Global Best:", global_best, global_best_score)

for iteration in range(1, max_iter + 1):

    for i in range(num_particles):


        r1, r2 = np.random.rand(), np.random.rand()

        velocities[i] = (
            w * velocities[i]
            + c1 * r1 * (personal_best[i] - particles[i])
            + c2 * r2 * (global_best - particles[i])
        )


        sigmoid = 1 / (1 + np.exp(-velocities[i]))


        particles[i] = (sigmoid > np.random.rand(num_features)).astype(int)


        score = evaluate(particles[i])


        if score > personal_best_scores[i]:
            personal_best[i] = particles[i].copy()
            personal_best_scores[i] = score


    best_idx = np.argmax(personal_best_scores)
    if personal_best_scores[best_idx] > global_best_score:
        global_best = personal_best[best_idx].copy()
        global_best_score = personal_best_scores[best_idx]

    print(f"Iteration {iteration}: Best = {global_best}  Acc = {global_best_score:.4f}")

print("\nFinal Best Feature Subset:", global_best, "Acc =", global_best_score)